import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
public class RegisterForm2 extends HttpServlet
{
   public void service(HttpServletRequest req,HttpServletResponse res)throws IOException,ServletException
  {   
   res.setContentType("text/html");
   PrintWriter out=res.getWriter();
   out.println("<html>");
  out.println("<head><title>registerForm2</title></head>");
 out.println("<body bgcolor=\"AliceBlue\">");
 out.println("<form action=\"http://localhost:4040/6prog/register1.jsp\">");
 out.println("<table align=\"center\" cellpadding=\"5\">");
 out.println("<tr><th colspan=\"2\"><img src=\"g.jpeg\" width=\"100\" height=\"100\" /></th></tr>");
 out.println("<tr><th colspan=\"2\"><h3>REGISTRATION FORM</h3></th></tr>");
 out.println("<tr><th>Login:</th><th><input type=\"text\" name=\"name\" /><br/></th></tr>");
 out.println("<tr><th>Password:</th><th><input type=\"password\" name=\"pwd\" /><br/></th></tr>");
 out.println("<tr><th>E-mail id:</th><th><input type=\"text\" name=\"mail\" /><br/></th></tr>");
 out.println("<tr><th>Phone number:</th><th><input type=\"text\" name=\"ph\" /><br/></th></tr>");
 out.println("<tr><th>Gender</th><th><input type=\"radio\" name=\"sex\" value=\"male\" />male");
         out.println("<input type=\"radio\" name=\"sex\" value=\"female\"/>female<br/></th></tr>"); 
 out.println(" <tr><th>DOB:</th><th><select>");
 out.println("<option value=\"1\">1</option>");
 out.println("<option value=\"2\">2</option>");
 out.println("<option value=\"3\">3</option>");
 out.println("<option value=\"4\">4</option>");
 out.println("<option value=\"5\">5</option>");
 out.println("<option value=\"6\">6</option>");
 out.println("<option value=\"7\">7</option>");
 out.println("<option value=\"8\">8</option>");
 out.println("<option value=\"9\">9</option>");
 out.println("<option value=\"10\">10</option>");
 out.println("<option value=\"11\">11</option>");
 out.println("<option value=\"12\">12</option>");
 out.println("<option value=\"13\">13</option>");
 out.println("<option value=\"14\">14</option>");
 out.println("<option value=\"15\">15</option>");
 out.println("<option value=\"16\">16</option>");
 out.println("<option value=\"17\">17</option>");
 out.println("<option value=\"18\">18</option>");
 out.println("<option value=\"19\">19</option>");
 out.println("<option value=\"20\">20</option>");
 out.println("<option value=\"21\">21</option>");
 out.println("<option value=\"22\">22</option>");
 out.println("<option value=\"23\">23</option>");
 out.println("<option value=\"24\">24</option>");
 out.println("<option value=\"25\">25</option>");
 out.println("<option value=\"26\">26</option>");
 out.println("<option value=\"27\">27</option>");
 out.println("<option value=\"28\">28</option>");
 out.println("<option value=\"29\">29</option>");
 out.println("<option value=\"30\">30</option>");
 out.println("<option value=\"31\">31</option>");
 out.println("</select>");
 out.println("<select> ");
 out.println("<option value=\"jan\">jan</option>");
 out.println("<option value=\"feb\">feb</option>");
 out.println("<option value=\"mar\">mar</option>");
 out.println("<option value=\"apr\">apr</option>");
 out.println("<option value=\"may\">may</option>");
 out.println("<option value=\"jun\">jun</option>");
 out.println("<option value=\"jul\">jul</option>");
 out.println("<option value=\"aug\">aug</option>");
 out.println("<option value=\"sep\">sep</option>");
 out.println("<option value=\"oct\">oct</option>");
 out.println("<option value=\"nov\">nov</option>");
 out.println("<option value=\"dec\">dec</option>");
 out.println("</select>");
 out.println("<select>");
 out.println("<option value=\"1990\">1990</option>");
 out.println("<option value=\"1991\">1991</option>");
 out.println("<option value=\"1992\">1992</option>");
 out.println("<option value=\"1993\">1993</option>");
 out.println("</select><br/></th></tr>");
 out.println("<tr><th rowspan=\"4\">langauges known</th><th>");
 out.println("<input type=\"checkbox\" name=\"english\" value=\"english\"       />english<br /></th></tr>");
 out.println("<tr><th><input type=\"checkbox\" name=\"telugu\" value=\"telugu\" />telugu<br/></th></tr> ");
 out.println("<tr><th><input type=\"checkbox\" name=\"hindi\" value=\"hindi\"   />hindi<br /></th></tr>");
 out.println("<tr><th><input type=\"checkbox\" name=\"tamil\" value=\"tamil\"   />tamil<br/></th></tr>");
 out.println("<tr><th>Address</th><th><textarea rows=\"10\" cols=\"40\" />address</textarea></th></tr>");
 out.println("<tr><th colspan=\"2\"><input type=\"submit\" value=\"Submit\" name=\"submit\" />");
 out.println("<input type=\"reset\" value=\"reset\" name=\"reset\" /><br/></th></tr>");
 out.println("</table></form>");
 out.println("</body></html>");
   out.close();
  }
  
} 